apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-lab
  labels:
    app: k8s-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-lab
  template:
    metadata:
      labels:
        app: k8s-lab
    spec:
      containers:
      - name: k8s-lab
        image: k8s-lab:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000