apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-lab
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: k8s-lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-lab
            port:
              number: 80