apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-lab-config
  namespace: staging
data:
  ENVIRONMENT: "staging"
  APP_VERSION: "2.0.0"
  DATABASE_URL: "postgresql://postgres:staging-postgres-password@postgres:5432/tododb"
  