apiVersion: v1
kind: Secret
metadata:
  name: k8s-lab-secret
  namespace: staging
type: Opaque
stringData:
  SECRET_KEY: "staging-secret-key-12345"
  DB_USER: "postgres"
  DB_PASSWORD: "staging-postgres-password"