apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-lab-config
  namespace: production
data:
  ENVIRONMENT: "production"
  APP_VERSION: "2.0.0"
  DATABASE_URL: "postgresql://postgres:production-postgres-password@postgres:5432/tododb"