apiVersion: v1
kind: Secret
metadata:
  name: k8s-lab-secret
  namespace: production
type: Opaque
stringData:
  SECRET_KEY: "production-secret-key-99999"
  DB_USER: "postgres"
  DB_PASSWORD: "production-postgres-password"