name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Debug files
        run: |
          pwd
          ls -la
          ls -la k8s/

      - name: Build immagine Docker
        run: |
          docker build -t k8s-lab:latest .

      - name: Importa immagine in k3s
        run: |
          docker save k8s-lab:latest | sudo k3s ctr images import -

      - name: Deploy su Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment/k8s-lab